version: "2"
run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly

linters:
  enable:
    - errcheck      # Checking for unchecked errors
    - govet         # Reports suspicious constructs
    - ineffassign   # Detects ineffectual assignments
    - staticcheck   # Advanced static analysis
    - unused        # Checks for unused code
    - misspell      # Finds commonly misspelled English words
    - revive        # Fast, configurable linter
    - gosec         # Security-focused linter
    - gocyclo       # Computes cyclomatic complexity
    - dupl          # Code clone detection
    - errname       # Checks error naming
    - errorlint     # Error wrapping
    - exhaustive    # Exhaustiveness checks
    - goconst       # Repeated strings detection
    - godot         # Comment punctuation
    - goprintffuncname # Printf-like functions
    - nolintlint    # Reports ill-formed nolint directives
    - predeclared   # Shadowed predeclared identifiers
    - unconvert     # Unnecessary type conversions
    - whitespace    # Whitespace issues
  settings:
    govet:
      disable-all: true
      enable:
        - shadow
        - assign
        - atomic
        - bools
        - buildtag
        - composites
        - copylocks
        - errorsas
        - httpresponse
        - loopclosure
        - lostcancel
        - nilfunc
        - printf
        - shift
        - stdmethods
        - stringintconv
        - structtag
        - tests
        - unmarshal
        - unreachable
        - unusedresult
    gocyclo:
      min-complexity: 15
    dupl:
      threshold: 100
    goconst:
      min-len: 3
      min-occurrences: 3
    misspell:
      locale: US
    revive:
      rules:
        - name: exported
          severity: warning
          disabled: false
        - name: unexported-return
          severity: warning
          disabled: false
    errcheck:
      check-type-assertions: true
      check-blank: true
  exclusions:
    rules:
      # Exclude some linters from running on tests files.
      - path: _test\.go
        linters:
          - gocyclo
          - dupl
          - gosec
          - goconst
          - errcheck
          - govet

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

output:
  formats:
    text:
      print-issued-lines: true
      print-linter-name: true
